:toc: macro
:toclevels: 5
:toc-placement!:

= mktrs-antora-tech-notes README

V2025.1.0

toc::[]

= Introduction
This tech notes site will document steps, guides, and central information at
hand in a day to day job.

This is a place to write everything I learn in a technical writing manner, not
a blog site, as a reference for our own studies.

This is an *_antora_* project to generate a static site for these resources.

To generate the site use the following command.

[IMPORTANT]
====
You must have the *_antora_* software installed to run the following commands
to generate the static site.

You can follow the steps required in this https://docs.antora.org/antora/latest/install/install-antora/[guide^],
use the antora documentation https://docs.antora.org/antora/latest/[Antora Docs^].

This is for the latest release, and as you would expect, it eats its own food. 
Check the version you need, or use the latest release.

You also need to always be sure to use the appropriate *_nodeJS_* version
required to run *_antora_*.

This is based in *_antora_* v3.1 or later.

In order to run the compilation of the site (commands shown next), you must be
located in the directory where the *_Playbooks_* are stored. In this project,
those files are under the *_docs_* folder.
====

[source, bash]
----
$ antora --fetch --clean site-master.yml
----

The output is stored in the *_build_* folder.

Where *_site.yml_* is the Antora Playbook.

* *site-local.yml:* Main Playbook, uses HEAD git ref.
* *site-develop:* Playbook using DEVELOP branch.
* *site-master:* Playbook using MASTER branch.
* *antora.yml:* Holds this doc book.

[NOTE]
====
Should you want to make changes to the book, but you don't want to commit
for every change in the reposository then use the *_antora playbook_*
file site-local.yml with the following command.

[source,bash]
----
$ antora --clean site-local.yml
----

====

Follow the next tip in order to start working in the *Antora* playbook,

[IMPORTANT]
====
When setting up the project for the first time you must commit first in order
to have contents generated, somehow if you use the command

[source,bash]
----
$ antora --clean site-local.yml
----

It can give you errors. So in order to work locally, you must first execute
the following command.

[source,bash]
----
$ antora --fetch --clean site-master.yml
----

====