= Quarkus

This is a page work in progress.
For now these are unedited blocks of text.

https://www.manning.com/liveproject/create-a-REST-API -> Manning Free content (requires an user account)

Intellij Quarkus Tools
https://plugins.jetbrains.com/plugin/13234-quarkus-tools

Use https://code.quarkus.io/ to bootstrap the project.

Creating your first Application
https://quarkus.io/guides/getting-started

Testing Your Application
https://quarkus.io/guides/getting-started-testing

RESTEasy Reactive
https://quarkus.io/guides/resteasy-reactive

Hibernate Validator
https://quarkus.io/guides/validation


Zulip
htpps://quarkusio.zulipchat.com

Quarkusio/Quarkus
https://github.com/quarkusio/quarkus
----------------------------------------------------------------------------------
References

Understanding Quarkus by Antonio Goncalves
https://developers.redhat.com/e-books/understanding-quarkus


Practising Quarkus by Antonio Goncalves
https://developers.redhat.com/e-books/practising-quarkus


Quarkus why, how, and what with Emmanuel Bernard (Intro to Quarkus by its createor)
https://www.youtube.com/watch?v=SQDR34KoC-8

Quarkus Insights (youtube channel)
https://www.youtube.com/quarkusio

----------------------------------------------------------------------------------


[NOTE]
====
The memory consumed by a process is called the resident set size (RSS). You can check it by 
using a ps -o pid,rss,command command. 
The value is in bytes, so to get a more “human-readable” version we recommend dividing 
the value by 1,024 to determine the number of megabytes.

Code
ps -o pid, rss, command | grep --color java | awk '{$2=int($2/1024)"M";}{print;}
====

Some other commands

$ mvn compile quarkus:dev

$ mvn quarkus:add-extensions -Dextensions=spring-web


Panache for JPA (like Spring Data JPA)

$ mvn package -Pnative -> Do a native image compilation.


http://localhost:8080/swagger-ui

include::ROOT:partial$lorem-ipsum.adoc[]

